# Old Config: TODO: Remove when new one is completely implemented, this is just here to get it to work with the current config in the images
#########################
# Rocket Pool Settings
providerPow: 'http://eth1.rpc.smartnode.localhost'

# New Config: Testnet
#########################
# Rocket Pool Settings
rocketpool:
  storageAddress: 0x2CaBe1D447092CB2A0740c30F43c68624B2cbaD4
# Chain Settings
# Clients supported have custom data fields in the 'params' object, the CLI & GUI will ask for these.
chains:
  # ETH1
  eth1:
    netID: 77
    provider: 'http://eth1.rpc.smartnode.localhost'
    clients:
      options:
        geth: 
            image: 'ethereum/client-go:v1.9.7'
            title: 'Geth'
            desc: 'made by the Ethereum Foundation'
            link: 'https://geth.ethereum.org'
        parity: 
            image: 'parity/parity:v2.5.10-stable'
            title: 'Parity'
            desc: 'made by Parity Technologies'
            link: 'https://www.parity.io'
        infura:
            title: 'Infura'
            desc: 'uses Infura as a light client for ETH1'
            link: 'https://infura.io'
            params:
                projectId: 
                    title: 'The Infura Project ID'
                    value: ''
      selected: false
    bootnodes:
      - 'enode://d5dcc1a6efd344e4f5b4d0a532773fad9497d4d9a9b5b7211eda551402cb8a541a707be4632990c4026ffb8975fcd599a3d36b7624ca1f709a434882f5cb7bca@3.216.221.20:30305'
      - 'enode://c2eae4a3c431bb5d6a404dd506f9442cb81ad38c9bd277bdd6511991fd713f321ddec1a92ee968cdf2f8c5628f985596088911d346265b0a279d87e3833cd989@3.216.221.20:30303'
    addresses:
      - deposit: '0x4FFFF1D447092CB2A0740c30F43c68624B2cFFFF'
    ethstats:
      - label: 'RP2Beta-Node'
      - login: 'rp2betav1ethstats@3.216.221.20'
  # ETH2
  eth2:
    provider: 'http://eth2.rpc.smartnode.localhost'
    clients:
        options:
            prysm: 
                image: 'prysmatic/client-go:v1.9.7'
                title: 'Prysm'
                desc: 'made by the Prysmatic Labs'
                link: 'https://prysmaticlabs.com/'
            lighthouse: 
                image: 'prime/v2.5.10-stable'
                title: 'Lighthouse'
                desc: 'made by Sigma Prime'
                link: 'https://sigmaprime.io/'
        selected: false


