version: "3.7"
services:
  traefik:
    image: traefik:v1.7.16
    command: [
      "--api",
      "--docker",
      "--docker.watch",
      "--docker.domain=smartnode.localhost",
    ]
    restart: always
    #ports:
    #  - "9080:8080" # Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net:
        aliases:
          - "eth1.rpc.smartnode.localhost"
  eth1:
    image: $(ETH1_IMAGE}
    restart: on-failure
    volumes:
      - eth1clientdata:/ethclient
      - ./chains/eth1:/setup:ro
    networks:
      - net
    environment:
      - CLIENT=$(ETH1_CLIENT}
      - NETWORKID=$(ETH1_NETWORK_ID}
      - BOOTNODE=$(ETH1_BOOTNODE}
      - ETHSTATSLABEL=$(ETH1_ETHSTATS_LABEL}
      - ETHSTATSLOGIN=$(ETH1_ETHSTATS_LOGIN}
    entrypoint: /setup/start-exec.sh
    labels:
      - traefik.enable=true
      - traefik.port=8545
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_net
      - traefik.frontend.priority=10
      - traefik.frontend.rule=Host:eth1.rpc.smartnode.localhost
      - traefik.backend.loadbalancer.stickiness=true
      - traefik.backend.loadbalancer.stickiness.cookieName=smartnodeEth1
      - traefik.backend.loadbalancer.method=drr
      - traefik.backend=eth1.rpc.smartnode
    depends_on:
      - traefik
  cli:
    image: rocketpool/smartnode-cli:v0.0.1
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
    networks:
      - net
    depends_on:
      - eth1
    entrypoint: /bin/sh
    tty: true
  minipools:
    image: rocketpool/smartnode-minipools:v0.0.1
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    command: [
      "${RP_PATH}",
      "rocketpool/smartnode-minipool:v0.0.1",
      "${COMPOSE_PROJECT_NAME}_minipool_",
      "${COMPOSE_PROJECT_NAME}_net",
    ]
    depends_on:
      - eth1
  node:
    image: rocketpool/smartnode-node:v0.0.1
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
    networks:
      - net
    depends_on:
      - eth1
  watchtower:
    image: rocketpool/smartnode-watchtower:v0.0.1
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
    networks:
      - net
    depends_on:
      - eth1
networks:
  net:
volumes:
  eth1clientdata:
