rocketpool:
  storageAddress: 0xbbCbc87447fE120E1Bc73dBd11bc4Dc1086FFa25
smartnode:
  passwordPath: /.rocketpool/data/password
  walletPath: /.rocketpool/data/wallet
  validatorKeychainPath: /.rocketpool/data/validators
chains:
  eth1:
    provider: http://eth1:8545
    client:
      options:
      - id: geth
        name: Geth
        desc: made by the Ethereum Foundation
        image: ethereum/client-go:v1.9.22
        link: https://geth.ethereum.org/
        params:
        - name: Ethstats Label
          desc: optional - for reporting Eth 1.0 node status to ethstats.net
          env: ETHSTATS_LABEL
        - name: Ethstats Login
          desc: optional - for reporting Eth 1.0 node status to ethstats.net
          env: ETHSTATS_LOGIN
      - id: infura
        name: Infura
        desc: uses infura.io as a light client for Eth 1.0 - not recommended for use in production
        image: rocketpool/smartnode-pow-proxy:v0.0.3
        link: https://infura.io/
        params:
        - name: Infura Project ID
          desc: the ID of your project created in Infura
          env: INFURA_PROJECT_ID
          regex: ^[0-9a-fA-F]{32}$
          required: true
  eth2:
    provider: eth2:5052
    client:
      options:
      - id: lighthouse
        name: Lighthouse
        desc: made by Sigma Prime
        image: sigp/lighthouse:v0.2.13
        link: https://sigmaprime.io/
        params:
        - name: Custom Graffiti
          desc: optional - for adding custom text to signed Eth 2.0 blocks
          env: CUSTOM_GRAFFITI
      - id: prysm
        name: Prysm
        desc: made by Prysmatic Labs
        beaconImage: gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-551b03-debug #v1.0.0-alpha.29
        validatorImage: gcr.io/prysmaticlabs/prysm/validator:HEAD-551b03-debug #v1.0.0-alpha.29
        link: https://prysmaticlabs.com/
        params:
        - name: Custom Graffiti
          desc: optional - for adding custom text to signed Eth 2.0 blocks
          env: CUSTOM_GRAFFITI
