rocketpool:
  storageAddress: 0x5709b6E58A390534c81dD8EE0E9E1423b843FF5a
  uniswapAddress: 0x6A603658DD351C65379A6fc9f7DD30742ae8bf3c
smartnode:
  databasePath: /.rocketpool/data/rocketpool.db
  passwordPath: /.rocketpool/data/password
  nodeKeychainPath: /.rocketpool/data/accounts
  validatorKeychainPath: /.rocketpool/data/validators
chains:
  eth1:
    provider: http://eth1.rpc.smartnode.localhost
    client:
      options:
      - name: Infura
        image: rocketpool/smartnode-pow-proxy:v0.0.1
      - name: Geth
        image: ethereum/client-go:stable
  eth2:
    provider: http://eth2.api.smartnode.localhost
    client:
      options:
      - name: Lighthouse
        image: sigp/lighthouse:latest
