rocketpool:
  storageAddress: 0x5709b6E58A390534c81dD8EE0E9E1423b843FF5a
  uniswapAddress: 0x6A603658DD351C65379A6fc9f7DD30742ae8bf3c
smartnode:
  databasePath: /.rocketpool/data/rocketpool.db
  passwordPath: /.rocketpool/data/password
  nodeKeychainPath: /.rocketpool/data/accounts
  validatorKeychainPath: /.rocketpool/data/validators
chains:
  eth1:
    provider: http://eth1.rpc.smartnode.localhost
    client:
      options:
      - id: geth
        name: Geth
        image: ethereum/client-go:stable
        desc: made by the Ethereum Foundation
        link: https://geth.ethereum.org
        params:
        - name: Ethstats Label
          env: ETHSTATS_LABEL
        - name: Ethstats Login
          env: ETHSTATS_LOGIN
      - id: infura
        name: Infura
        image: rocketpool/smartnode-pow-proxy:v0.0.1
        desc: uses Infura as a light client for ETH1
        link: https://infura.io
        params:
        - name: Infura Project ID
          env: INFURA_PROJECT_ID
          regex: ^[0-9a-fA-F]{32}$
          required: true
  eth2:
    provider: http://eth2.api.smartnode.localhost
    client:
      options:
      - id: lighthouse
        name: Lighthouse
        image: sigp/lighthouse:testnet5
        desc: made by Sigma Prime
        link: https://sigmaprime.io/
