
global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
scrape_configs:
  # Prometheus  
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
        - targets: ['localhost:9090']
  # Node Exporter - Local Metrics
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    dns_sd_configs:
        - names:
          - 'rocketpool_metrics_nodexporter'  # This must be the containers name
          type: 'A'
          port: 9100
  # Traefik
  - job_name: 'traefik'
    scrape_interval: 5s
    dns_sd_configs:
        - names:
          - 'rocketpool_traefik' # This must be the containers name
          type: 'A'
          port: 8080
  # Smart Node
  #- job_name: 'smartnode'
  #  scrape_interval: 5s
  #  dns_sd_configs:
  #      - names:
  #        - 'rocketpool_metrics' # This must be the containers name, for some reason changing it to any frontend results in it pointing to traefik
  #        type: 'A'
  #        port: 2115
  
    # Free space % | 100 - ((node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"})
    # CPU Usage % | 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="nodeexporter",mode="idle"}[5m])) * 100)
    # Mem usage % | 100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[10m]) + avg_over_time(node_memory_Cached_bytes[10m]) + avg_over_time(node_memory_Buffers_bytes[10m])) / avg_over_time(node_memory_MemTotal_bytes[10m])))